export const track_oss = [
    {
        id: '01',
        active: 'active',
        title: 'OSS Talk Flutter Vs ReactNative',
        podName: 'The OSS Community - ',
        date: '11/11/2022',
        fileUrl: 'https://raw.githubusercontent.com/muhammederdem/mini-player/master/mp3/5.mp3',
    },
    {
        id: '02',
        active: '',
        title: 'Cross-Platform Development',
        podName: 'The OSS Community -',
        date: '10/09/2022',
        fileUrl: 'https://raw.githubusercontent.com/muhammederdem/mini-player/master/mp3/6.mp3',
    },
    {
        id: '03',
        active: '',
        title: 'Recent OSS Developement',
        podName: 'The OSS Community -',
        date: '01/01/2022',
        fileUrl: 'https://raw.githubusercontent.com/muhammederdem/mini-player/master/mp3/4.mp3',
    },
    {
        id: '04',
        active: '',
        title: 'FronEnd Development Stack',
        podName: 'The OSS Community - ',
        date: '08/08/2022',
        fileUrl: 'https://raw.githubusercontent.com/muhammederdem/mini-player/master/mp3/3.mp3',
    },
    {
        id: '05',
        title: 'Back-End Development Stack',
        podName: 'The OSS Community -',
        date: ' 07/03/2022',
        fileUrl: 'https://raw.githubusercontent.com/muhammederdem/mini-player/master/mp3/2.mp3',
    },
    {
        id: '06',
        title: 'Full-Stack Development Guides',
        podName: 'The OSS Community -',
        date: ' 02/05/2022',
        fileUrl: 'https://raw.githubusercontent.com/muhammederdem/mini-player/master/mp3/1.mp3',
    },
    {
        id: '07',
        title: 'Full-Stack Development Guides',
        podName: 'The OSS Community -',
        date: ' 02/05/2022',
        fileUrl: 'https://raw.githubusercontent.com/muhammederdem/mini-player/master/mp3/1.mp3',
    },
    {
        id: '08',
        title: 'Full-Stack Development Guides',
        podName: 'The OSS Community -',
        date: ' 02/05/2022',
        fileUrl: 'https://raw.githubusercontent.com/muhammederdem/mini-player/master/mp3/1.mp3',
    },
    {
        id: '09',
        title: 'Full-Stack Development Guides',
        podName: 'The OSS Community -',
        date: ' 02/05/2022',
        fileUrl: 'https://raw.githubusercontent.com/muhammederdem/mini-player/master/mp3/1.mp3',
    },
    {
        id: '10',
        title: 'Full-Stack Development Guides',
        podName: 'The OSS Community -',
        date: ' 02/05/2022',
        fileUrl: 'https://raw.githubusercontent.com/muhammederdem/mini-player/master/mp3/1.mp3',
    },
    {
        id: '11',
        title: 'Full-Stack Development Guides',
        podName: 'The OSS Community -',
        date: ' 02/05/2022',
        fileUrl: 'https://raw.githubusercontent.com/muhammederdem/mini-player/master/mp3/1.mp3',
    },
    {
        id: '12',
        title: 'Full-Stack Development Guides',
        podName: 'The OSS Community -',
        date: ' 02/05/2022',
        fileUrl: 'https://raw.githubusercontent.com/muhammederdem/mini-player/master/mp3/1.mp3',
    },
    {
        id: '13',
        title: 'Full-Stack Development Guides',
        podName: 'The OSS Community -',
        date: ' 02/05/2022',
        fileUrl: 'https://raw.githubusercontent.com/muhammederdem/mini-player/master/mp3/1.mp3',
    },
]